### PR TITLE
v0.5

### PR DESCRIPTION
**Pull request by ThePrez**

### CODE REVIEW

**Comment by chrjorgensen** [comment]
Hi @ThePrez 

What is the purpose of this PR - autorestart a service? Interesting... 😃

**Comment by ThePrez** [comment]
I committed things to the wrong branch and was too lazy to manage it properly. Thank you for keeping me accountable! 

The major feature here is that one can ship a sc definition (`.yaml` file) adjacent to the solution and create symlinks from `/QOpenSys/etc/sc/services` or `$HOME/.sc/services`. So, a product can ship a definition with `dir: .` and it can be placed anywhere on the filesystem. Before this change, if the filesystem location changed, the YAML would need to be changed too. 

This branch also had the `screbash` utility, which was a horrible first attempt at auto-restarting of services.

**Comment by ThePrez** [comment]
For an example use case, see
https://github.com/ThePrez/Prometheus-client-IBMi
and more specifically https://github.com/ThePrez/Prometheus-client-IBMi/blob/main/src/main/resources/com/ibm/jesseg/prometheus.yml

**Comment by chrjorgensen** [comment]
@ThePrez 

> Thank you for keeping me accountable!

That's what I'm here for! 😆 

Great idea of symlinks to a product SC definition file! 😍 
And looking forward to further attempts of restart... 👍

**Pull request merged**
