### PR TITLE
Fix wrong logfile name

### PR DESCRIPTION
**Pull request by chrjorgensen**
## Explain the reasoning for this pull request. For instance, is it for a new feature, bug fix, code style/cleanup, or something else? If fixing an open issue, please link to it here.

This PR will fix issue #203

### CODE REVIEW

**Comment by ThePrez** [comment]
Thanks for the discovery and PR! 
I haven't had time to "page into" this and re-examine the use of the timestamp formats, but would it be sufficient to keep only one (`DB_TIMESTAMP_FORMAT`) and just change it to the new value?

**Comment by chrjorgensen** [comment]
Unfortunately DB2 and Java use different symbols for the minutes and 24 hour, so one template can not be used for both timestamp formatters.

That's the reason for having two templates.

**Comment by chrjorgensen** [comment]
To expand on my previous comment, I also think that having two constants/templates demonstrates the difference between the timestamp formatters, so no one else will be caught by this.

**Comment by ThePrez** [comment]
@chrjorgensen just FYI this is still on my radar. I hope to review and get this landed later this week.

**Comment by chrjorgensen** [comment]
@ThePrez No worry - enjoy the Christmas break!

**Review by ThePrez — APPROVED** [review]
LGTM! Thank you!

**Pull request merged**
