### PR TITLE
Capture output of STRTCPSVR when running interactively

### LINKED ISSUE #117: [BUG] STRTCPSVR doesn't show `sc` output in 5250
See #115/#116 for some context, but the reason the STRTCPSVR handler sometimes runs in non-batch mode is because during bringup, I was able to see sc progress messages, warnings, etc. 

Even outside the scope of STRTCPSVR, I can't get this desired behavior. For instance, if I run:
```
CALL PGM(QP2SHELL ) PARM('/QOpenSys/pkgs/bin/bash' '-l' '-c'            
        'echo hi && exec /QOpenSys/pkgs/bin/sc start zookeeper 2>&1 |cat
;echo done  ;sleep 5'                  )                                
``
... the "hi" and "done" show on the screen but the `sc` output does not!! 😠 
cc @chrjorgensen for awareness/input

### PR DESCRIPTION
**Pull request by ThePrez**
Fixes #117. 
@chrjorgensen , please review. Thanks!

### CODE REVIEW

**Comment by ThePrez** [comment]
(never mind the JAva bugfixes I have on this same branch; I am too lazy to move them)

**Review by chrjorgensen — COMMENTED** [review]
@ThePrez Looking good - but is it necessary to go through QSHELL to run a PASE program?

In his UNIXCMD tool Scott Klement is calling the PASE environment (argument 1: '/qsys.lib/qp2shell.pgm' and argument 2: '/qopensys/usr/bin/sh') after setting QIBM_USE_DESCRIPTOR_STDIO=I and QIBM_PASE_DESCRIPTOR_STDIO=T.

So it is possible to go directly to the PASE environment... which in my opinion is better since this is a PASE tool.

What's your thoughts on this?

**Comment by ThePrez** [comment]
@chrjorgensen good find! I will experiment with this tomorrow. Not going through qshell would be great

**Comment by ThePrez** [comment]
@chrjorgensen that works great! Requesting review of the change

**Review by chrjorgensen — APPROVED** [review]
Nice! 🥇

**Pull request merged**
