### PR TITLE
allow options to be set in ~/.scrc and /QOpenSys/etc/sc/scrc

### PR DESCRIPTION
**Pull request by ThePrez**

### CODE REVIEW

**Comment by chrjorgensen** [comment]
I've just tried using the SC_OPTIONS environment instead - `export SC_OPTIONS="-v"` - and now command `sc info crond` runs in verbose mode... so there is no problem identifying the arguments coming from the command line, just from the `scrc` local and global files.

**Comment by ThePrez** [comment]
Yep, you understood the objective of the changes perfectly. I tested with very similar steps as you have. Looks like the code is just not working  👎

**Comment by ThePrez** [comment]
@chrjorgensen , in the catch block in the new `getOptionsFromConfigFiles()` method, can you add `e.printStackTrace();` and see if that gives us any clues? 
I initially thought, maybe it's an EBCDIC issue (always suspect EBCDIC on IBM i!!) but if that were the case, I'd expect it to parse "garbage" arguments and give you warnings about them. And the files clearly exist as you have shown. :/

**Review by chrjorgensen — COMMENTED** [review]
According to my latest test, the code is working - please confirm it is also working on your system.

**Comment by ThePrez** [comment]
All good! Thanks!

**Pull request merged**
