### PR TITLE
totally redo how log files are handled

### PR DESCRIPTION
**Pull request by ThePrez**
This PR started out as a PR to make `loginfo` more reliable but ended up being much more:
- Add `log_dir` configuration option to the YAML schema (tells sc where to send its logs)
- Reasonably resolve default log location when submitting to batch as a different user, so that other user has permission to write to log files
- Add `runattrs` operation
- beef up `perfinfo` output

### CODE REVIEW

**Comment by jwoehr** [comment]
SCLogFile.java
Line 89:  `catch (final InterruptedException e)` etc.
Line 102: `catch (final IOException e)` etc.

You don't want to leave traps that catch exceptions you didn't think about the first cut of the file.

**Comment by jwoehr** [comment]
`public abstract class ServiceDefinition`
.......
 ```
 public String getConfiguredLogDirectory() {
        return null;
    }
```
If it's an abstract class, do you really need a definition body that returns `null`?

**Comment by jwoehr** [comment]
`class ProcessLauncher`
I think some of the stream handling is convoluted and that there are more approbated patterns for this, but maybe I should produce some example code or shut up.

**Comment by jwoehr** [comment]
QueryUtils.java:
```
    private static List<String> deduplicate(final List<String> _in) {
        final HashSet<String> s = new HashSet<String>();
        s.addAll(_in);
        return Arrays.asList(s.toArray(new String[0]));
    }
```
could be
```
 private static List<String> deduplicate (final List<String> _in) {
      return    new List<>(new LinkedHashSet<>(_in));
}
```
or something like that.

**Comment by jwoehr** [comment]
QueryUtils.java 

NetBeans points out:

line 297:  ` synchronized (s_cacheLock)` ... synchronization on non-final
line 303: `final Set<Integer> openPorts = new LinkedHashSet<Integer>();` you can use diamonds here instead of types

**Comment by ThePrez** [comment]
@jwoehr , thanks for all the comments! 
I checked in some changes to address some concerns, but failed to address two of them: 

First:
https://github.com/ThePrez/ServiceCommander-IBMi/pull/161#issuecomment-1093702550
I couldn't find these lines in ScLogFile, and I didn't understand a good alternative implementation for some of the "wonky" exception handling as it were

Second: 
https://github.com/ThePrez/ServiceCommander-IBMi/pull/161#issuecomment-1093710066
Great catch on the synchronization on non-final! 
I'm keeping the code the same, but will openly admit it's only crotchety programming. I heavily dislike the usage of diamonds (`<>`) as it makes the code less comprehensible (yes, that's an incredibly subjective and unpopular opinion!). I prefer when the typing is explicit rather than implicit. 

I'm going to merge this PR in and start working on another feature, but feel free to continue code review discussion here if desired. Thanks!

**Comment by jwoehr** [comment]
@ThePrez this is what I was suggesting about ScLogFile:
```
--- a/src/main/java/jesseg/ibmi/opensource/ScLogFile.java
+++ b/src/main/java/jesseg/ibmi/opensource/ScLogFile.java
@@ -91,7 +91,7 @@ public class ScLogFile {
                     }
                     Thread.sleep(100);
                 }
-            } catch (final Exception e) {
+            } catch (final InterruptedException e) {
                 _logger.printExceptionStack_verbose(e);
             }
         });
@@ -104,7 +104,7 @@ public class ScLogFile {
             final Process p = Runtime.getRuntime().exec(new String[] { "/QOpenSys/usr/bin/tail", "-f", m_file.getAbsolutePath() });
             ProcessLauncher.pipeStreamsToCurrentProcess(m_file.getName(), p, _logger);
             Runtime.getRuntime().addShutdownHook(new Thread(() -> p.destroy()));
-        } catch (final Exception e) {
+        } catch (final IOException e) {
             _logger.printExceptionStack_verbose(e);
         }
     }
```
One doesn't want to catch `Exception` as it's a bug lying in wait.

**Comment by ThePrez** [comment]
@jwoehr thank you! That was definitely not intentional

**Comment by jwoehr** [comment]
Thanks for not scolding me for being too lazy to submit an actual PR

**Pull request merged**
